website/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
	# /music/
	url(r'^$', views.index, name="index"),
	# /music/21
	url(r'^(?P<album_id>[0-9]+)/$', views.detail, name="detail"),

	# /music/<album_id>/favorite
	url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name="favorite"),
]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^music/', include('music.urls')),
    url(r'^admin/', admin.site.urls),
]

website/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	albumTitle = models.CharField(max_length=200)
	genre = models.CharField(max_length=100)
	albumLogo = models.CharField(max_length=500)

	def __str__(self):
		return self.albumTitle + "-" + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=200)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

website/music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Album

# Create your views here.
def index(request):
	all_albums = Album.objects.all()
	context = {'all_albums': all_albums,}
	return render(request, 'music/index.html', context)

# detail function, passing album_id regex group as param
def detail(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	return render(request, 'music/detail.html', {'album':album,})

# Favorite song view
def favorite(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	try:
		selected_song = album.song_set.get(pk=request.POST['song']) # gets id of song
		print(request.POST['song'])
	except (KeyError, Song.DoesNotExist):
		return render(request, 'music/detail.html', {
			'album': album, 
			'error_message': "You did not enter valid song",
			})
	else:
		selected_song.is_favorite = True
		selected_song.save()
		return render(request, 'music/detail.html', {'album': album,})

website/music/templates/music/detail.html
<img src="{{ album.album_logo }}" alt="taylor swift" height="100px" width="100px">
<h1>{{ album.albumTitle }}</h1>
<h2>{{ album.artist }}</h2>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
{% csrf_token %}
{% for song in album.song_set.all %}
	<input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}" />
	<label for="song{{forloop.counter}}">
		{{song.song_title}}		
		{% if song.is_favorite %}
		<img src="http://www.pngpix.com/wp-content/uploads/2016/10/PNGPIX-COM-Star-PNG-Transparent-Image-2-500x500.png" height="16px" width="16px">
		{% endif %}
	</label><br>
{% endfor %}	
<input type="submit" value="Favorite">
</form>

website/music/templates/music/index.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<!-- Loads the static files -->
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'music/css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- logo -->
		<div class="navbar-header">
			<a href="{% url 'music:index' %}" class="navbar-brand">Mozoo</a>
		</div>
	</div>
</nav>

{% if all_albums %}
<h2>Here are my albums.</h2>
<ul>
	{% for album in all_albums %}
	<li><a href="{% url 'music:detail' album.id %}">{{ album.albumTitle }}</a></li>
	{% endfor %}
</ul>
{% else %}
<h2>There are no albums.</h2>
{% endif %}
</body>
</html>